services:
  # Web Service
  - type: web
    name: babyfoot-club
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: babyfoot-db
          property: connectionString

databases:
  # PostgreSQL Database (GRATUIT 500 MB)
  - name: babyfoot-db
    plan: free
    databaseName: babyfoot
    user: babyfoot_user
